[tool.black]
line-length = 100
target-version = ['py39']

[tool.ruff]
target-version = "py39"
line-length = 100

[tool.ruff.lint]
# E=pycodestyle, F=pyflakes, I=isort, UP=pyupgrade, B=bugbear
select = ["E", "F", "I", "UP", "B"]
# Blackと競合するルールは無効化
ignore = ["E203", "E501"]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["wanstage"]
