name: auto-post
on:
  schedule:
    - cron: '0 0 * * *' # 00:00 UTC = 09:00 JST
  workflow_dispatch:
    inputs:
      to:
        description: 'Target: slack | x | instagram'
        required: true
        default: 'slack'
      text:
        description: 'Message to post'
        required: true
        default: '定期投稿（手動実行）'
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - name: Post (scheduled)
        if: ${{ github.event_name == 'schedule' }}
        run: |
          node --no-warnings --experimental-strip-types ./src/post.ts \
            --to=${{ vars.DEFAULT_TO || 'slack' }} \
            "定期投稿 $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
      - name: Post (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          node --no-warnings --experimental-strip-types ./src/post.ts \
            --to="${{ github.event.inputs.to }}" \
            "${{ github.event.inputs.text }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
