name: checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node/TS/ESLint/Prettier/HTML Validate
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run check:ts
      - run: npm run check:js
      - run: npm run check:html

      # Python (Ruff/Black)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install ruff black
      - run: python -m ruff check .
      - run: python -m black --check .
