name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt || true
          pip install ruff black mypy pytest pytest-xdist coverage \
            types-requests types-PyYAML types-python-dateutil
      - name: Lint & Format
        run: |
          ruff --output-format=github .
          black --check .
      - name: Type check
        run: mypy
      - name: Tests
        run: pytest -q -n auto
      - name: Slack notify (optional)
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          MSG="CI: ${{ github.workflow }} @ ${{ github.ref }} -> ${{ job.status }}"
          curl -s -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"${MSG}\"}" "$SLACK_WEBHOOK_URL" || true
