name: Debug Trace CI

on:
  workflow_dispatch:
    inputs:
      include_lfs:
        description: "LFS objects to fetch (comma-separated globs)"
        required: false
        default: ""
  push:
    branches: [ main ]

jobs:
  debug-trace:
    runs-on: ubuntu-latest
    env:
      GIT_LFS_SKIP_SMUDGE: "1"
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Checkout (skip LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Selective LFS fetch (only if requested)
        if: ${{ github.event.inputs.include_lfs != '' }}
        run: |
          git lfs install --skip-smudge
          git lfs fetch --include="${{ github.event.inputs.include_lfs }}" --exclude=""
          git lfs checkout || true
          git lfs fsck || true

      - name: Tool setup
        run: |
          npm ci || npm i
          pipx install pre-commit || true

      - name: Run debug trace
        id: trace
        continue-on-error: true
        run: |
          mkdir -p logs
          chmod +x scripts/run_debug_trace.sh
          ./scripts/run_debug_trace.sh

      - name: Upload trace logs
        uses: actions/upload-artifact@v4
        with:
          name: trace-logs
          path: logs/trace_log_*.log

      - name: Slack notification (only when webhook is set)
        if: ${{ always() && env.SLACK_WEBHOOK != '' }}
        run: |
          st="✅ 成功"
          [ "${{ job.status }}" != "success" ] && st="❌ 失敗"
          set +H 2>/dev/null || true
          printf '{"text":"[Debug Trace CI] %s\nrepo: %s\nrun: %s"}' \
            "$st" "$GITHUB_REPOSITORY" "$GITHUB_RUN_ID" \
          | curl -sS -H 'Content-Type: application/json' -d @- "$SLACK_WEBHOOK" \
          || echo "[WARN] slack post failed"
