name: wanstage release
on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: false

permissions: { contents: write }
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug contexts
        shell: bash
        run: |
          set -e
          echo "::group::github"; echo "event=${GITHUB_EVENT_NAME}"; echo "ref=${GITHUB_REF}"; echo "ref_name=${GITHUB_REF_NAME}"; echo "::endgroup::"

      - name: Resolve TAG
        shell: bash
        run: |
          set -euo pipefail
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" && -n "${{ github.event.inputs.tag }}" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${GITHUB_REF_NAME:-}"
          fi
          [[ -n "${TAG:-}" ]] || { echo "[error] TAG not resolved"; exit 1; }
          echo "TAG=${TAG}"       >> "$GITHUB_ENV"
          echo "TAG_NO_V=${TAG#v}" >> "$GITHUB_ENV"

      - name: Produce minimal artifacts
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p out
          printf "WANSTAGE release bundle for %s\n" "${TAG}" > "out/README_${TAG}.txt"
          tar -czf "release_all_${TAG}.tar.gz" -C out .
          (cd out && zip -r "../release_all_${TAG}.zip" . >/dev/null)
          shasum -a 256 "release_all_${TAG}.tar.gz" "release_all_${TAG}.zip" > "SHA256SUMS_${TAG}.txt"

      - name: Upload release (minimal)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          generate_release_notes: true
          fail_on_unmatched_files: false
          files: |
            release_all_${{ env.TAG }}.tar.gz
            release_all_${{ env.TAG }}.zip
            SHA256SUMS_${{ env.TAG }}.txt
