name: release (tag → build → upload)

on:
  push:
    tags:
      - 'v*'
      - 'V*'
      - '*-r*'
      - '*-fix*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag name (e.g., v20250926)'
        required: true

permissions:
  contents: write   # ← Release 作成に必須

jobs:
  release:
    if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
    steps:
      - name: Checkout (with tags)
        uses: actions/checkout@v4
        with:fetch-depth: 0 fetch-tags: true name: Show context
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"
          echo "TAG=${TAG}"
          git tag --list | tail -n +1- name: Build minimal artifacts
        run: |
          mkdir -p artifacts
          echo "WANSTAGE minimal artifact for ${TAG} ($(date -u +%FT%TZ))" > artifacts/README_release_${TAG}.txt
          tar -czf artifacts/release_all_${TAG}.tar.gz -C artifacts README_release_${TAG}.txt
          ( cd artifacts && zip -q release_all_${TAG}.zip README_release_${TAG}.txt )
          sha256sum artifacts/* > artifacts/SHA256SUMS_${TAG}.txt
 - name: Optional minisign
        if: ${{ secrets.MINISIGN_PUBLIC && (secrets.MINISIGN_SECRET || secrets.MINISIGN_SECRET_BASE64) }}
        run: |
          sudo apt-get update && sudo apt-get install -y minisign
          mkdir -p ~/.minisign_keys
          if [[ -n "${MINISIGN_SECRET_BASE64:-}" ]]; then
            echo "$MINISIGN_SECRET_BASE64" | base64 -d > ~/.minisign_keys/minisign_seckey.txt
          elif [[ -n "${MINISIGN_SECRET:-}" ]]; then
            printf "%s" "$MINISIGN_SECRET" > ~/.minisign_keys/minisign_seckey.txt
          fi
          chmod 600 ~/.minisign_keys/minisign_seckey.txt
          printf "%s" "$MINISIGN_PUBLIC" > artifacts/minisign_pubkey.txt
          for f in artifacts/release_all_${TAG}.tar.gz artifacts/release_all_${TAG}.zip; do
            minisign -Sm "$f" -s ~/.minisign_keys/minisign_seckey.txt -m "$f"
          done
        env:
          MINISIGN_PUBLIC: ${{ secrets.MINISIGN_PUBLIC }}
          MINISIGN_SECRET: ${{ secrets.MINISIGN_SECRET }}
          MINISIGN_SECRET_BASE64: ${{ secrets.MINISIGN_SECRET_BASE64 }}
  - name: Create or update GitHub Release and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # 既存確認 → 無ければ作成
          if gh release view "${TAG}" >/dev/null 2>&1; then
            echo "Release ${TAG} already exists."
          else
            gh release create "${TAG}" --title "${TAG}" --notes "Automated release for ${TAG}"
          fi   gh release upload "${TAG}" artifacts/* --clobber

      - name: List uploaded assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release view "${TAG}" --json assets,name,tagName,url
