name: wanstage release (minimal-safe)

on:
  push:
    tags:
      - 'v*'   # タグ push で実行
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g. v20250926-rX)"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ここでタグ名を安全に決定（式は使わず bash 内で完結）
      - name: Determine TAG
        run: |
          set -euo pipefail
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG="${{ inputs.tag }}"
          else
            # push(tag) のときは GITHUB_REF_NAME にタグ名が入っている
            TAG="${GITHUB_REF_NAME}"
          fi
          if [[ -z "${TAG}" ]]; then
            echo "TAG is empty" >&2
            exit 1
          fi
          echo "TAG=${TAG}" | tee -a "$GITHUB_ENV"

      - name: Build minimal artifacts
        run: |
          set -euo pipefail
          mkdir -p out
          printf "WANSTAGE release bundle for %s\n" "${TAG}" > "out/README_${TAG}.txt"
          tar -czf "release_all_${TAG}.tar.gz" -C out .
          (cd out && zip -r "../release_all_${TAG}.zip" . > /dev/null)
          shasum -a 256 "release_all_${TAG}.tar.gz" "release_all_${TAG}.zip" > "SHA256SUMS_${TAG}.txt"

      # 任意: pack-by-category があれば追記（無ければ何もしない）
      - name: Optional pack-by-category
        run: |
          set -euo pipefail
          if [[ -x ./pack-by-category.zsh && -f ./categories_latest.csv ]]; then
            echo "[info] run pack-by-category.zsh ..."
            ./pack-by-category.zsh -c ./categories_latest.csv -o "${TAG#v}" || echo "[warn] pack failed (ignored)"
          else
            echo "[info] pack-by-category not present -> skip"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          generate_release_notes: true
          files: |
            release_all_*.tar.gz
            release_all_*.zip
            SHA256SUMS_*.txt
