name: sns-auto-post

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Post target'
        default: 'slack'
        options: ['slack', 'x', 'instagram']
      message:
        description: 'Message to post'
        default: "手動投稿: ${GITHUB_REPOSITORY} $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  schedule:
    - cron: '0 0 * * *' # 00:00 UTC = 09:00 JST

jobs:
  # 手動実行（target単発）
  manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: npm ci
      - name: Post to ${{ inputs.target }}
        run: |
          node --no-warnings --experimental-strip-types ./src/post.ts \
            --to=${{ inputs.target }} "${{ inputs.message }}"
        env:
          TZ: Asia/Tokyo
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Zapier webhook（X/IGのネイティブ鍵が無いときのフォールバック）
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
          # --- X(Twitter) 直投げ用（任意） ---
          X_APP_KEY: ${{ secrets.X_APP_KEY }}
          X_APP_SECRET: ${{ secrets.X_APP_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          # --- Instagram Graph API 直投げ用（任意） ---
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}

  # 定期実行（毎朝に slack/x/instagram を順番に）
  daily:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        to: [slack, x, instagram]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: npm ci
      - name: Post to ${{ matrix.to }}
        run: |
          MSG="定期投稿 ${GITHUB_REPOSITORY} $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          node --no-warnings --experimental-strip-types ./src/post.ts --to=${{ matrix.to }} "$MSG"
        env:
          TZ: Asia/Tokyo
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
          X_APP_KEY: ${{ secrets.X_APP_KEY }}
          X_APP_SECRET: ${{ secrets.X_APP_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
