name: wanstage-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node（JS/TS）
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci

      # Python（Ruff/Black がある場合だけ実行）
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - run: |
          python -m pip install --upgrade pip
          pip install ruff black || true

      # Lint / Format チェック（失敗で止める）
      - name: ESLint
        run: npx eslint . --max-warnings=0

      - name: Ruff
        run: ruff check .

      - name: Black (check)
        run: black --check .

      - name: TypeScript typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Tests
        run: |
          if npm run -s test:ci >/dev/null 2>&1; then
            npm run -s test:ci
          elif npm run -s test >/dev/null 2>&1; then
            npm run -s test
          else
            echo "(no tests) — skipping"
          fi
