name: weekly-summary
on:
  schedule:
    - cron: '5 0 * * 1'
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - name: Weekly summary
        env:
          SHEET_ID: ${{ vars.SHEET_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # どれか1つを設定（B64 / JSON / FILE）
          GOOGLE_SERVICE_ACCOUNT_B64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_B64 }}
          # GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          # GOOGLE_SERVICE_ACCOUNT_FILE:  # （使うなら actions/download-artifact か repo secrets/file を工夫）
        run: node --no-warnings --experimental-strip-types ./src/weekly-summary.ts
